### ISSUE TITLE
Chomium - Aw, Snap! Error code: SIGTRAP

### ISSUE THREAD

**Issue by TheGiolly** [accetto/ubuntu-vnc-xfce-g3#20]
Hello,
first of all thanks for the beautiful container!

I'm facing a problem with Chromium: it gives me `Aw, Snap! Error code: SIGTRAP` when I try to browse any website.
Using noVNC full, container created with `docker create --name=ubuntu -p 5901:5901 -p 6901:6901 accetto/ubuntu-vnc-xfce-chromium-g3`.

![Immagine 2022-01-22 210022](https://user-images.githubusercontent.com/9699045/150653904-c06c1f91-4e5e-48cc-8b04-563be055241e.png)

**Comment by accetto** [comment]
Hello,

I was not able to reproduce the issue (s. the screenshot). Have you tried it under Linux or Windows?

I would say, that the problem is the following part of your command: `-p 5901:5901 -p 6901:6901 `.

Bind to some other ports on your host, for example with the parameter `-P`, like

`docker run --name=ubuntu -P accetto/ubuntu-vnc-xfce-chromium-g3`

Then your container will use the next free TCP ports on your host. You can find out which ones with the command 
`docker ps`.

Please let me know, if it helped.

Regards,
accetto

![Capture](https://user-images.githubusercontent.com/34798830/150848980-8c6d8045-e4de-4960-b48d-d10b0a851dd8.JPG)

**Comment by lacek** [comment]
Ran into the same issue. The port mapping isn't the cause but the shared memory. Default `shm_size` is only 64MB, add the `--shm-size` param with a larger value fixes the problem, e.g. `docker run -it--name=ubuntu -p 5901:5901 -p 6901:6901 --shm-size 1g accetto/ubuntu-vnc-xfce-chromium-g3`.
