### ISSUE TITLE
[SOLVED] unusable - multiple bugs and issues

### ISSUE THREAD

**Issue by KlausGlueckert** [accetto/ubuntu-vnc-xfce-g3#53]
`./builder.sh latest-firefox build` fails due to
* missing execution rights +x
* `./docker/hooks/env.rc: line 31: REPO_OWNER_NAME: Need repo owner name`

`docker run -d -p 5901:5901 -p 6901:6901  --rm accetto/ubuntu-vnc-xfce-firefox-g3:22.04` fails:
* no logs shown in container
* grey screen when logging in with headless password

**Comment by accetto** [comment]
You're too fast with your conclusions. Causes of all you problems can be tracked down to your environment and your current level of knowledge.

1. It's not unusual, that the file settings need some adjustments after cloning from the GitHub repository. Please make all the files in the folder `./docker/hooks/` executable. Actually, the file `env.rc` doesn't need it, but you can include it too. Do the same for all the `*.sh` files.

1. The message `REPO_OWNER_NAME: Need repo owner name` means that at least the environment variable `REPO_OWNER_NAME` needs to be set. It's all described in the readme files and the Wiki.

1. I do not recommend to bind the ports `5901` and `6901` to the same ports of the host computer. Use some other free ports from the higher range or leave the binding options out and Docker will find some free ports automatically.

You can find all the answers in the readme files, the Wiki and the [User Guide](https://accetto.github.io/user-guide-g3/).

**Comment by accetto** [comment]
Hello @KlausGlueckert,

I've just experienced a little schock, because I've got exactly the messages, you've described above, on one of my machines.

It wanted to build containers using `ci-builder.sh` on a Windows 10 system and I've opened the project in WSL2 (Ubuntu 22-04 LTS).

However, after checking-out the commit labeled `v23.08` and then the latest commit labeled `v23.08.1` again, everything worked fine.

So it seems to be related to the latest Docker Desktop updates, maybe.

I never had something like that before.

Regards,
accetto
