### ISSUE TITLE
Redirect to novnc full client

### ISSUE THREAD

**Issue by kulmann** [accetto/ubuntu-vnc-xfce-g3#60]
According to the docs noVNC offers a full and a lite client. Is there a way to skip the choice and always use e.g. the full client? I'm currently building my own docker image based on your `accetto/ubuntu-vnc-xfce-g3:latest` image and have it running in a `compose` stack. Both build time and runtime config change would work. Thank you!

**Comment by accetto** [comment]
Hello @kulmann ,

thank you for your feedback. If I've understood you well, you want to skip the `noVNC` connect screen.

Under normal circumstances you wouldn't need to change anything in the images. Just access the running container using the full URL as it's described in the [User Guide](https://accetto.github.io/user-guide-g3/) on the page [Using web browser](https://accetto.github.io/user-guide-g3/using-novnc/).

However, it shows up, that the `noVNC` **full** client currently doesn't process the password from the access URL correctly.

There was already the [issue #1839](https://github.com/novnc/noVNC/issues/1839) about it, so I've also added my comment there. Hopefully they will fix it soon.

For now you can use the **lite** client, if it helps.

Regards,
accetto

**Comment by samhed** [comment]
If I understand @kulmann's question, it's not about the connect screen. I think he is asking if the choice between `vnc_lite.html` (lite UI) or `vnc.html` (full UI) could be skipped.

**Comment by kulmann** [comment]
Thanks a lot to both of you @accetto and @samhed for looking at my issue!

> If I understand @kulmann's question, it's not about the connect screen. I think he is asking if the choice between `vnc_lite.html` (lite UI) or `vnc.html` (full UI) could be skipped.

Yes, exactly this. I'm almost certain that my users won't understand which one to choose, so I'd like the container to immediately redirect to either the light or the full ui.

I don't care too much, which one it will be (although I'd opt for the full UI `vnc.html`), as long as the password prompt is the first thing my users get presented. If that's not possible via config or build params, I'll find an external solution (traefik is in place already anyway), but I'd prefer a built in solution. :-)

**Comment by accetto** [comment]
I see. In that case you would need to modify the images. There are several possibilities.

Basically you have to replace the file `index.html` by the file `vnc.html` in the directory defined by the environment variable `NOVNC_HOME`.

Because I find your hint generally useful, I would like to offer also some compromise solution. I've uploaded the following temporary images, that automatically redirect to the full client after 5 seconds. Could you check them please and let me know, how do you find it?

- [accetto/ubuntu-vnc-xfce-g3:issue-60](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-g3/tags)
- [accetto/ubuntu-vnc-xfce-chromium-g3:issue-60](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium-g3/tags)
- [accetto/ubuntu-vnc-xfce-firefox-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox-g3/tags)

I would also like to mention, that the correct connection link to the full client including the password is `vnc.html?autoconnect=true&password=headless`. My User Guide is not up-to-date in this part. Thanks to @samhed for the hint.

**Comment by accetto** [comment]
All images since the release **24.09** automatically redirect to the full client after 10 seconds.
